logging:
  config: classpath:log4j2.xml

server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:file:~/h2/management
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  #  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
