eureka:
  client:
    service-url:
      - http://localhost:8761/eureka
server:
  port: 0
spring:
  datasource:
    url: jdbc:h2:file:~/h2/inventory
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: inventory-service