logging:
  level:
    root: info
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:file:./TestDataBase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
        