eureka:
  client:
    service-url:
      - http://localhost:8761/eureka
server:
  port: 0
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:~/h2/order
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect