server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 1KB
  datasource:
    url: jdbc:h2:file:~/h2/testing
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect