# create basic configuation for application


server:
  # address: 0.0.0.0
  port: 8080
  servlet:
    # context-path: /api/v1
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 1KB
  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: spring-boot-actuator
  datasource:
    url: jdbc:h2:file:~/h2/store
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

####