project:
  poster: poster/
  fileFormat: png

logging:
  level:
    root: info

spring:
  cache:
    type: REDIS
    redis:
      time-to-live: 6_00_000 # 10 min cache
      cache-null-values: false
  data:
    redis:
      host: localhost
      port: 6379
      password: password

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/h2/movie-api
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  #  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
