spring:
  datasource:
    url: jdbc:h2:file:~/h2/soap
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  #  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create